version: "3.9"

services:
  db:
    image: postgres:15
    container_name: cinema_postgres
    restart: always
    environment:
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_pass
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
